language: cpp

matrix:
  include:
    - env: TRCC=gcc   TRCXX=g++
    - env: TRCC=clang TRCXX=clang++
    - env: TRCC=gcc   TRCXX=g++     TRHOST="i586-mingw32msvc"
    - env: TRCC=clang TRCXX=clang++ TRHOST="i586-mingw32msvc"
  allow_failures:
    - env: TRCC=clang TRCXX=clang++
    - env: TRCC=clang TRCXX=clang++ TRHOST="i586-mingw32msvc"
  fast_finish: true


before_install:
  - uname -a
  - lsb_release --all

install:
  - ${TRAVIS_BUILD_DIR}/install-dependencies.sh

script:
  - export CC=$TRCC
  - export CXX=$TRCXX
  - export HOST=$TRHOST
  - export PATH=/usr/$HOST/bin:$PATH
  - ${TRAVIS_BUILD_DIR}/build-o-matic.sh

